theme: "jekyll-theme-clean-blog"
title: Samuel Turner
#email: your-email@example.com
description: Software Testing. Linux. Gaming. Overclocking.
author: Samuel Turner
baseurl: "/"
url: "https://samuel-turner.co.uk"

# Social Profiles
twitter_username: SamuelTurner_
github_username: SamuelTurner

# Add your google-analytics ID here to activate google analytics
google_analytics: UA-21961367-1

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  